(function () {
  "use strict";

  function card(id, deck, topic, front, back, example, tags, hint) {
    return {
      id: id,
      deck: deck,
      topic: topic,
      front: front,
      back: back,
      example: example || "",
      tags: tags || [],
      hint: hint || "",
      starter: true
    };
  }

  window.HTML_CSS_SEED_CARDS = [
    card("html-doctype", "HTML Foundations", "Document structure", "What does the HTML doctype do?", "<!doctype html> tells the browser to render the document in standards mode. It is a declaration, not an HTML element, and should be the first line of the file.", "<!doctype html>", ["document", "standards"], "It prevents quirks mode."),
    card("html-lang", "HTML Foundations", "Document structure", "Why should the <html> element have a lang attribute?", "It declares the document's primary language so screen readers choose the right pronunciation rules and browsers or search engines can process the page correctly.", "<html lang=\"en\">", ["accessibility", "document"], "Think pronunciation and translation."),
    card("html-head-body", "HTML Foundations", "Document structure", "What belongs in <head>, and what belongs in <body>?", "The head contains document metadata and linked resources such as the title, description, stylesheet links, and charset. The body contains the content rendered as the page.", "<head>\n  <title>Page title</title>\n</head>\n<body>\n  <h1>Visible heading</h1>\n</body>", ["document", "metadata"]),
    card("html-charset", "HTML Foundations", "Metadata", "Why is <meta charset=\"utf-8\"> normally placed near the start of <head>?", "It tells the browser how to decode the document. Placing it early lets the browser interpret subsequent bytes correctly without restarting the parse.", "<meta charset=\"utf-8\">", ["metadata", "encoding"]),
    card("html-viewport", "HTML Foundations", "Metadata", "What problem does the viewport meta tag solve on mobile?", "It tells mobile browsers to use the device width as the layout viewport instead of presenting a scaled-down desktop-width page.", "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">", ["mobile", "metadata"], "Without it, responsive CSS may appear zoomed out."),
    card("html-attributes", "HTML Foundations", "Elements", "What is the difference between an HTML element and an attribute?", "An element defines structure or meaning, while an attribute adds configuration or metadata to an element. Attributes appear in the start tag and usually use name=\"value\" syntax.", "<a href=\"/learn\" aria-current=\"page\">Learn</a>", ["elements", "attributes"]),
    card("html-void", "HTML Foundations", "Elements", "What is a void element? Name three examples.", "A void element cannot contain child content and has no closing tag. Examples include <img>, <input>, <meta>, <link>, <br>, and <hr>.", "<img src=\"portrait.jpg\" alt=\"Jordan smiling\">", ["elements", "syntax"]),
    card("html-urls", "HTML Foundations", "Links and paths", "When should you use a relative URL instead of an absolute URL?", "Use a relative URL for resources within the same site so the link follows the current origin or directory. Use an absolute URL when the protocol and hostname must be explicit, commonly for external sites.", "<a href=\"../index.html\">Home</a>\n<a href=\"https://example.com\">External site</a>", ["links", "paths"]),
    card("html-data-attributes", "HTML Foundations", "Attributes", "What are data-* attributes for?", "They store private, page-specific data on an element for CSS or JavaScript. JavaScript reads them through element.dataset. They should not replace semantic attributes that already exist.", "<button data-action=\"delete\">Delete</button>\n\nconst action = button.dataset.action;", ["attributes", "javascript"]),
    card("html-comments-entities", "HTML Foundations", "Syntax", "How do HTML comments and character references differ?", "A comment adds source notes that are not rendered. A character reference represents a character that would otherwise be ambiguous or inconvenient in markup, such as &lt; or &amp;.", "<!-- This is a source comment -->\n<p>Use &amp;lt; to display &lt;.</p>", ["syntax", "entities"]),

    card("semantic-main", "Semantic HTML", "Landmarks", "What is the purpose of the <main> element?", "It identifies the dominant content of the document. A page should normally have one visible main landmark, allowing assistive-technology users to jump past repeated navigation.", "<main id=\"main\">\n  <h1>Article title</h1>\n</main>", ["semantic", "landmarks", "accessibility"]),
    card("semantic-nav", "Semantic HTML", "Landmarks", "When should a group of links be wrapped in <nav>?", "Use <nav> for a major navigation block, such as the primary site menu, table of contents, or pagination. Not every small group of links needs to be a navigation landmark.", "<nav aria-label=\"Primary\">\n  <a href=\"/\">Home</a>\n  <a href=\"/learn\">Learn</a>\n</nav>", ["semantic", "navigation", "landmarks"]),
    card("semantic-article-section", "Semantic HTML", "Content sections", "How do <article> and <section> differ?", "An article is self-contained content that could stand independently or be syndicated. A section is a thematic grouping within a document and should normally have a heading.", "<article>\n  <h2>News story</h2>\n  <section>\n    <h3>Background</h3>\n  </section>\n</article>", ["semantic", "structure"]),
    card("semantic-headings", "Semantic HTML", "Headings", "What makes a good heading hierarchy?", "Headings describe the outline of the content. Start with a clear h1 for the page, then nest sections logically without choosing heading levels for their visual size.", "<h1>CSS guide</h1>\n<section>\n  <h2>Layout</h2>\n  <h3>Grid</h3>\n</section>", ["headings", "accessibility", "seo"]),
    card("semantic-lists", "Semantic HTML", "Lists", "When should you use <ul>, <ol>, and <dl>?", "Use ul when order is not meaningful, ol when sequence or ranking matters, and dl for name-value groups such as terms and definitions or metadata pairs.", "<dl>\n  <dt>Status</dt>\n  <dd>Complete</dd>\n</dl>", ["semantic", "lists"]),
    card("semantic-figure", "Semantic HTML", "Media", "What relationship do <figure> and <figcaption> express?", "A figure wraps self-contained media or illustrative content, while figcaption provides its associated caption. The figure can be referenced as one unit from the surrounding content.", "<figure>\n  <img src=\"chart.png\" alt=\"Sales rose each quarter\">\n  <figcaption>Quarterly sales for 2026.</figcaption>\n</figure>", ["semantic", "images"]),
    card("semantic-time", "Semantic HTML", "Text semantics", "Why use the datetime attribute on <time>?", "It gives machines a standardized date or time while allowing the visible text to use a reader-friendly format.", "<time datetime=\"2026-07-10\">10 July 2026</time>", ["semantic", "dates", "metadata"]),
    card("semantic-details", "Semantic HTML", "Disclosure", "What do <details> and <summary> provide without JavaScript?", "They provide a native disclosure widget. Summary is the visible control and the remaining details content expands or collapses with keyboard and pointer support built in.", "<details>\n  <summary>Show explanation</summary>\n  <p>The browser handles this interaction.</p>\n</details>", ["semantic", "interaction", "accessibility"]),
    card("semantic-table", "Semantic HTML", "Tables", "Which elements make a data table understandable?", "Use caption for the table's purpose, th for headers, scope to associate simple row or column headers, and tbody or thead to group rows. Use tables for data, not page layout.", "<table>\n  <caption>Study totals</caption>\n  <thead><tr><th scope=\"col\">Deck</th><th scope=\"col\">Cards</th></tr></thead>\n  <tbody><tr><th scope=\"row\">HTML</th><td>30</td></tr></tbody>\n</table>", ["semantic", "tables", "accessibility"]),
    card("semantic-button-link", "Semantic HTML", "Interaction", "When should an interface use a button instead of a link?", "Use a link to navigate to another URL or document location. Use a button to perform an action such as opening a dialog, saving data, or changing interface state.", "<a href=\"/learn\">Open the deck</a>\n<button type=\"button\">Shuffle cards</button>", ["semantic", "buttons", "links", "accessibility"]),

    card("form-label", "HTML Forms & Accessibility", "Forms", "How should a label be associated with a form control?", "Give the control an id and set the label's for attribute to the same value, or place the control inside the label. An explicit association is often easiest to maintain and gives the control an accessible name.", "<label for=\"email\">Email</label>\n<input id=\"email\" name=\"email\" type=\"email\">", ["forms", "labels", "accessibility"]),
    card("form-fieldset", "HTML Forms & Accessibility", "Forms", "When are <fieldset> and <legend> useful?", "They group related controls and give the group an accessible name. They are especially useful for radio-button groups or sections of a longer form.", "<fieldset>\n  <legend>Preferred layout</legend>\n  <label><input type=\"radio\" name=\"layout\" value=\"grid\"> Grid</label>\n</fieldset>", ["forms", "grouping", "accessibility"]),
    card("form-input-type", "HTML Forms & Accessibility", "Forms", "Why choose the most specific input type?", "Specific types provide appropriate mobile keyboards, built-in semantics, and basic validation. Examples include email, url, number, date, search, and password.", "<input type=\"email\" name=\"email\" autocomplete=\"email\">", ["forms", "input", "mobile"]),
    card("form-name", "HTML Forms & Accessibility", "Forms", "What does a form control's name attribute do?", "It supplies the key used when the browser submits that control's value. An enabled input without a name is normally omitted from submitted form data.", "<input name=\"username\" value=\"Jordan\">\n<!-- submits username=Jordan -->", ["forms", "submission"]),
    card("form-validation", "HTML Forms & Accessibility", "Forms", "Why is client-side validation not enough on its own?", "Browser validation improves feedback, but clients can bypass or alter it. The server must validate all submitted data again before trusting, storing, or acting on it.", "<input name=\"age\" type=\"number\" min=\"18\" required>", ["forms", "validation", "security"]),
    card("form-autocomplete", "HTML Forms & Accessibility", "Forms", "What does autocomplete communicate to the browser?", "It identifies the expected purpose of a field so browsers and password managers can offer accurate autofill. Values such as name, email, current-password, and postal-code are standardized tokens.", "<input type=\"password\" autocomplete=\"current-password\">", ["forms", "autocomplete", "accessibility"]),
    card("form-button-type", "HTML Forms & Accessibility", "Forms", "Why should buttons inside a form usually declare their type?", "A button defaults to type=submit in a form. Declare type=button for non-submit actions to avoid accidental submissions, or type=submit when submission is intended.", "<button type=\"button\">Add another row</button>\n<button type=\"submit\">Save</button>", ["forms", "buttons"]),
    card("a11y-alt", "HTML Forms & Accessibility", "Images", "What makes useful alt text?", "Alt text communicates the image's purpose in context, not every visual detail. Use alt=\"\" for decorative images so screen readers skip them; do not omit alt from meaningful images.", "<img src=\"warning.svg\" alt=\"Build failed\">\n<img src=\"divider.svg\" alt=\"\">", ["images", "alt", "accessibility"]),
    card("a11y-aria", "HTML Forms & Accessibility", "ARIA", "What is the first rule of ARIA?", "Prefer a native HTML element with the required semantics and behavior before adding ARIA. ARIA can change accessibility semantics, but it does not add keyboard behavior or visual presentation by itself.", "<!-- Prefer this -->\n<button type=\"button\">Save</button>\n\n<!-- over a clickable div with role=button -->", ["aria", "semantic", "accessibility"]),
    card("a11y-live", "HTML Forms & Accessibility", "ARIA", "When is aria-live=\"polite\" useful?", "It asks assistive technology to announce dynamic text after the current announcement finishes. Use it for meaningful status updates such as saved changes or updated result counts, not constantly changing decoration.", "<p id=\"save-status\" aria-live=\"polite\"></p>", ["aria", "dynamic", "accessibility"]),

    card("css-cascade", "CSS Foundations", "Cascade", "Which factors decide which CSS declaration wins?", "The cascade considers origin and importance, cascade layer, specificity, scoping proximity where applicable, and then source order. A later declaration only wins when the earlier cascade factors tie.", ".card { color: navy; }\n.card { color: green; } /* wins by source order */", ["cascade", "specificity"]),
    card("css-specificity", "CSS Foundations", "Cascade", "How is selector specificity compared?", "IDs outrank classes, attributes, and pseudo-classes, which outrank type selectors and pseudo-elements. Compare each category rather than treating specificity as one base-10 number.", "#app .card p { color: rebeccapurple; }", ["specificity", "selectors"], "Think ID, class, type columns."),
    card("css-inheritance", "CSS Foundations", "Cascade", "What does CSS inheritance mean?", "Some properties take the computed value from the parent when the child has no specified value. Text properties often inherit; layout properties such as margin and border generally do not.", "body { color: #111827; }\n/* Paragraph text inherits the color. */", ["inheritance", "cascade"]),
    card("css-box-model", "CSS Foundations", "Box model", "What are the four layers of the CSS box model?", "From inside to outside they are content, padding, border, and margin. Backgrounds extend through the padding and underneath the border, but not into the margin.", ".card {\n  padding: 1rem;\n  border: 1px solid;\n  margin: 1rem;\n}", ["box-model", "layout"]),
    card("css-box-sizing", "CSS Foundations", "Box model", "What changes when box-sizing is border-box?", "The declared width and height include content, padding, and border. This makes component sizing more predictable than the default content-box model.", "*, *::before, *::after {\n  box-sizing: border-box;\n}", ["box-model", "sizing"]),
    card("css-units", "CSS Foundations", "Values and units", "When are rem, em, %, vw, and px useful?", "rem scales from the root font size, em from the current element's font size, percentages depend on a containing context, viewport units track the viewport, and px is a CSS reference pixel useful for precise details such as thin borders.", "h1 { font-size: clamp(2rem, 5vw, 4rem); }", ["units", "responsive"]),
    card("css-custom-properties", "CSS Foundations", "Values and units", "What makes CSS custom properties different from preprocessor variables?", "Custom properties participate in the cascade, inherit by default, and remain available at runtime. They can be changed by selectors, media queries, or JavaScript.", ":root { --accent: #4e8b5b; }\n.button { background: var(--accent); }", ["custom-properties", "cascade"]),
    card("css-pseudo", "CSS Foundations", "Selectors", "How do pseudo-classes and pseudo-elements differ?", "A pseudo-class selects an element in a state or relationship, such as :hover or :focus-visible. A pseudo-element represents a part or generated box, such as ::before or ::first-line.", "a:focus-visible { outline: 3px solid; }\n.card::before { content: \"\"; }", ["selectors", "pseudo-class", "pseudo-element"]),
    card("css-hidden", "CSS Foundations", "Display", "How do display: none and visibility: hidden differ?", "display: none removes the element's box from layout and the accessibility tree in normal circumstances. visibility: hidden keeps its layout space but hides it and its descendants from interaction.", ".removed { display: none; }\n.reserved-space { visibility: hidden; }", ["display", "visibility", "accessibility"]),
    card("css-overflow", "CSS Foundations", "Box model", "What does overflow control?", "It defines what happens when content does not fit an element's box. Values include visible, hidden, clip, auto, and scroll, and can be set separately for each axis.", ".code-sample {\n  overflow-x: auto;\n}", ["overflow", "layout"]),

    card("layout-normal-flow", "CSS Layout", "Normal flow", "What is normal flow?", "It is the default layout system before special positioning or flex/grid is applied. Block boxes generally stack in the block direction, while inline content flows within lines.", "article > * + * { margin-block-start: 1rem; }", ["normal-flow", "layout"]),
    card("layout-flex-axes", "CSS Layout", "Flexbox", "What are the main axis and cross axis in Flexbox?", "The main axis follows flex-direction. The cross axis is perpendicular to it. justify-content distributes items on the main axis, while align-items controls them on the cross axis.", ".row {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n}", ["flexbox", "alignment"]),
    card("layout-flex-shorthand", "CSS Layout", "Flexbox", "What do the three values in flex: 1 1 20rem mean?", "They are flex-grow, flex-shrink, and flex-basis. The item may grow, may shrink, and starts calculations from a 20rem preferred base size.", ".item { flex: 1 1 20rem; }", ["flexbox", "sizing"]),
    card("layout-grid-fr", "CSS Layout", "Grid", "What does the fr unit represent in Grid?", "It represents a fraction of the leftover space in the grid container after fixed sizes, gaps, and intrinsic constraints are accounted for.", ".grid {\n  display: grid;\n  grid-template-columns: 2fr 1fr;\n}", ["grid", "units"]),
    card("layout-grid-autofit", "CSS Layout", "Grid", "What pattern creates a responsive grid without a media query?", "repeat(auto-fit, minmax(...)) creates as many tracks as fit and lets them expand. A minimum such as min(16rem, 100%) prevents overflow in narrow containers.", ".grid {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(min(16rem, 100%), 1fr));\n}", ["grid", "responsive"]),
    card("layout-gap", "CSS Layout", "Spacing", "Why is gap often preferable to margins between flex or grid children?", "Gap belongs to the container, creates spacing only between tracks or items, and avoids edge-margin exceptions. It also works in flex, grid, and multi-column layouts.", ".cluster { display: flex; gap: 0.75rem; }", ["gap", "spacing", "flexbox", "grid"]),
    card("layout-position", "CSS Layout", "Positioning", "How do relative, absolute, fixed, and sticky positioning differ?", "Relative keeps the element in flow and offsets it from its normal position. Absolute removes it from flow and positions it against a containing block. Fixed is normally viewport-relative. Sticky behaves in flow until a scroll threshold is reached.", ".header { position: sticky; top: 0; }", ["position", "layout"]),
    card("layout-z-index", "CSS Layout", "Stacking", "Why can a very large z-index still fail to place an element on top?", "z-index is compared within stacking contexts. A child cannot escape its parent's stacking context to outrank an element in another higher context, regardless of the child's numeric value.", ".modal { position: fixed; z-index: 100; }", ["z-index", "stacking-context"]),
    card("layout-margin-collapse", "CSS Layout", "Spacing", "When can vertical margins collapse?", "Adjacent block margins in normal flow can combine into a single margin. Flex and grid item margins do not collapse, and padding, borders, or a new formatting context can prevent collapse.", ".stack > * + * { margin-block-start: 1rem; }", ["margin", "normal-flow"]),
    card("layout-minmax", "CSS Layout", "Sizing", "What is the practical difference between width and max-width?", "width sets a preferred or definite size, while max-width caps how large the used width may become. Combining width: 100% with max-width creates a fluid element with an upper limit.", ".wrap {\n  width: min(100% - 2rem, 70rem);\n  margin-inline: auto;\n}", ["sizing", "responsive"]),

    card("responsive-mobile-first", "Responsive CSS", "Responsive design", "What does mobile-first CSS mean?", "Base styles support smaller or simpler layouts first, then min-width queries add enhancements as space becomes available. It reduces overrides and starts from the most constrained environment.", ".grid { display: grid; }\n@media (min-width: 48rem) {\n  .grid { grid-template-columns: 1fr 1fr; }\n}", ["responsive", "media-query"]),
    card("responsive-media", "Responsive CSS", "Media queries", "What should determine a media-query breakpoint?", "Choose a breakpoint where the content or layout stops working well, not one based only on a named device. Content-driven breakpoints remain useful as device sizes change.", "@media (min-width: 52rem) {\n  .sidebar-layout { grid-template-columns: 2fr 1fr; }\n}", ["responsive", "media-query"]),
    card("responsive-container", "Responsive CSS", "Container queries", "How does a container query differ from a media query?", "A media query responds to the viewport or device environment. A container query responds to the size or style of an ancestor container, making a component adapt to where it is placed.", ".card-list { container-type: inline-size; }\n@container (min-width: 32rem) {\n  .card { grid-template-columns: 1fr 2fr; }\n}", ["responsive", "container-query", "components"]),
    card("responsive-clamp", "Responsive CSS", "Fluid values", "How does clamp(minimum, preferred, maximum) help responsive design?", "It creates a fluid value that can grow with a relative preferred expression but never goes below the minimum or above the maximum.", "h1 { font-size: clamp(2.25rem, 7vw, 5rem); }", ["responsive", "functions", "typography"]),
    card("responsive-object-fit", "Responsive CSS", "Media", "What does object-fit: cover do to an image?", "It scales a replaced element to cover its content box while preserving aspect ratio. Some of the image may be cropped. Give the box an explicit size or aspect ratio for the effect to be visible.", ".thumbnail {\n  width: 100%;\n  aspect-ratio: 16 / 9;\n  object-fit: cover;\n}", ["images", "responsive", "object-fit"]),
    card("responsive-logical", "Responsive CSS", "Internationalization", "Why use logical properties such as margin-inline and padding-block?", "They describe layout relative to writing direction instead of physical left, right, top, and bottom. This makes components adapt more naturally to right-to-left or vertical writing modes.", ".card {\n  padding-block: 1rem;\n  padding-inline: 1.5rem;\n}", ["logical-properties", "internationalization"]),
    card("responsive-motion", "Responsive CSS", "User preferences", "How should prefers-reduced-motion affect an interface?", "Use it to remove or substantially reduce non-essential animation for people who request less motion. Preserve important state changes without relying on movement alone.", "@media (prefers-reduced-motion: reduce) {\n  *, *::before, *::after {\n    scroll-behavior: auto;\n    transition-duration: 0.01ms;\n  }\n}", ["accessibility", "motion", "media-query"]),
    card("responsive-contrast", "Responsive CSS", "Colour", "What are the usual WCAG AA contrast targets for text?", "Normal text should reach at least 4.5:1 against its background. Large text should reach at least 3:1. Interface components and meaningful graphics also commonly need 3:1 against adjacent colours.", "/* Test the final rendered foreground and background pair. */", ["accessibility", "contrast", "color"]),
    card("responsive-layers", "Responsive CSS", "Cascade", "What problem do cascade layers solve?", "@layer gives groups of author styles an explicit precedence order before selector specificity is compared. This can keep resets, third-party styles, components, and utilities predictable without specificity battles.", "@layer reset, base, components, utilities;\n\n@layer components {\n  .button { padding: 0.75rem 1rem; }\n}", ["cascade", "layers", "architecture"]),
    card("responsive-content-visibility", "Responsive CSS", "Performance", "When can content-visibility: auto improve rendering performance?", "It lets the browser skip layout and painting for off-screen content until needed. It is most useful on long pages with independent sections; pair it carefully with intrinsic-size hints to reduce scrollbar shifts.", ".long-section {\n  content-visibility: auto;\n  contain-intrinsic-size: auto 600px;\n}", ["performance", "rendering", "containment"])
  ];
})();
